name: send
description: A Flutter package to help deploy and manage Continuous Integration (CI) processes
version: 0.0.1
homepage: https://github.com/SamadiPour/send
repository: https://github.com/SamadiPour/send
issue_tracker: https://github.com/SamadiPour/send/issues
topics: [cli, continuous integration, deployment, app-store, google-play]

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.6.0
  yaml_edit: ^2.2.1

dev_dependencies:
  test: ^1.25.8
  lints: ^5.0.0
